### ISSUE TITLE
关于新功能：本地显示职位初次浏览时间，历史浏览次数

### ISSUE THREAD

**Issue by lastsunday** [tangzhiyao/boss-show-time#22]
目的：

1. 实现本地记录曾经浏览的岗位，在搜索页上显示初次浏览时间以及曾经浏览的次数
2. 实现本地记录的查询和统计

相关的合并请求：

1. https://github.com/tangzhiyao/boss-show-time/pull/23

实现效果：

![image](https://github.com/lastsunday/boss-show-time/assets/5588354/c5a720ae-7602-4c2b-85b3-caa87e780f16)

调研的问题：

1. 是否需要该功能？
3. 对该功能是否有详细的要求和建议？如页面显示效果，功能性要求。

当前可预见的相关技术细节：

1. 岗位的唯一标识问题，该取哪些字段或字段组合作为唯一主键？
2. 使用什么技术作为持久化存储？（涉及查询效率，可存储的最大容量）(下面以sqlite作为持久化存储为例)
    1. 使用[sqlite-wasm](https://github.com/sqlite/sqlite-wasm)实现数据库的访问。
    2. sqlite的schema自动更新的实现。
    4. 数据库schema的设计。

**Comment by tangzhiyao** [comment]
👍🏻执行力真的很强
就我个人而言，不是很在意看过的职位。不过之前确实看到有人提过，我这几天看下代码，发上去试试看用的人有没有什么建议
