### ISSUE TITLE
关于新功能：岗位评论

### ISSUE THREAD

**Issue by lastsunday** [tangzhiyao/boss-show-time#24]
目的：

1. 实现岗位的评论，点赞

相关的合并请求：

相关演示效果临时分支：

https://github.com/lastsunday/boss-show-time/tree/feature/comment

实现效果：

![preview01](https://github.com/tangzhiyao/boss-show-time/assets/5588354/41a2b504-9fc9-496d-b68d-8238ebbfb7d9)

![preview02](https://github.com/tangzhiyao/boss-show-time/assets/5588354/2499d901-8e08-4c05-adce-053e47193f8b)

调研的问题：

1. 是否需要该功能？
2. 对该功能是否有详细的要求和建议？如页面显示效果，功能性要求。

当前可预见的相关技术细节：

1. 岗位的唯一标识问题，该取哪些字段或字段组合作为唯一主键？
2. 使用哪个评论平台？如：https://0xecho.com/
3. 需要补充MetaMask的使用说明和如何登录到ECHO平台。
    1. ECHO官网：https://0xecho.com/
    2. MetaMask官网：https://metamask.io/
    3. MetaMask的Chrome插件https://github.com/MetaMask/metamask-extension/releases 
5. echo平台的使用是否有限制？

**Comment by tangzhiyao** [comment]
功能是很好
也是有两个问题
1. 合规的问题，最好还是自己能控制，避免一些敏感信息
2. 登录不太友好，注册这一步就限制了不少人，这样评论本身其实就有点失去意义了
3. 个人感觉 Gitment 似乎还可以
https://shuiba.co/comment-systems-recommendation
