### ISSUE TITLE
浏览器导入插件报错

### ISSUE THREAD

**Issue by m-x-h** [tangzhiyao/boss-show-time#3]
![image](https://github.com/tangzhiyao/boss-show-time/assets/52300785/1051a4f9-100a-4066-82f4-8b496737c6f6)

**Comment by zeonghost** [comment]
刚导入后我也看到了这个报错，但去到boss里插件是正常运行的

**Comment by m-x-h** [comment]
我试了下可以用，感谢!

**Comment by tangzhiyao** [comment]
报错不影响，已经在修复了
