### ISSUE TITLE
feature:增加油猴版本

### ISSUE THREAD

**Issue by chainray01** [tangzhiyao/boss-show-time#30]
大佬考虑增加油猴版本吗，这个安装更方便一点

**Comment by lastsunday** [comment]
你好，你可以试用一下这个，复现了基础功能（显示发布时间，排序和快捷查找公司信息）。

https://greasyfork.org/zh-CN/scripts/498159-job-hunting

**Comment by shuiyunwudi** [comment]
> 你好，你可以试用一下这个，复现了基础功能（显示发布时间，排序和快捷查找公司信息）。
> 
> https://greasyfork.org/zh-CN/scripts/498159-job-hunting

这个插件怎么用呢？不懂前端。

**Comment by lastsunday** [comment]
> > 你好，你可以试用一下这个，复现了基础功能（显示发布时间，排序和快捷查找公司信息）。
> > https://greasyfork.org/zh-CN/scripts/498159-job-hunting
> 
> 这个插件怎么用呢？不懂前端。

这个是油猴脚本，需要安装另外的浏览器插件（如：[篡改猴 (Tampermonkey) ](https://www.tampermonkey.net/index.php?locale=zh)）后，再访问上面的脚本地址进行安装。

**_注意事项：油猴的脚本市场存在很多奇奇怪怪的东西，请认真甄别所安装的脚本，以确保安全_**
