### ISSUE TITLE
console output error when run npm run build command

### ISSUE THREAD

**Issue by yunxiangnian** [tangzhiyao/boss-show-time#32]
这是我遇到的问题，我看了下文件夹里没有 build script，是不是没有放进去呢？还麻烦解答下，谢谢
<img width="873" alt="image" src="https://github.com/tangzhiyao/boss-show-time/assets/50510739/4e149e1c-55e8-4c7e-8d20-bb03f68e2c03">

**Comment by tangzhiyao** [comment]
分支拉错了，用main
